parameters:
    app.path.recipes_img: /uploads/images/recipes
    app.path.users_img: /uploads/images/profiles_pictures

vich_uploader:
    db_driver: orm
    metadata:
        type: attribute

    mappings:
        recipe_img:
            uri_prefix: '%app.path.recipes_img%'
            upload_destination: '%kernel.project_dir%/public%app.path.recipes_img%'
        user_img:
            uri_prefix: '%app.path.users_img%'
            upload_destination: '%kernel.project_dir%/public%app.path.users_img%'
